window.__AIROPEWAY_SERVICE_CATEGORIES__ = [
  { id: 'sales', label: 'Sales', icon: '🚀' },
  { id: 'marketing', label: 'Marketing', icon: '📣' },
  { id: 'operations', label: 'Operations', icon: '⚙️' },
  { id: 'transformation', label: 'Business Transformation', icon: '🔁' },
];

window.__AIROPEWAY_SERVICES__ = [
  {
    id: 'S1',
    category: 'sales',
    name: 'AI SDR-as-a-Service',
    tagline: 'Your Always-On Sales Rep',
    description:
      'Replace 2–3 manual SDRs with a fully managed AI outreach system. We handle everything from ICP definition and list building to email warm-up, sequencing, inbox management, and weekly performance reporting. KPI: meetings booked per month.',
    outcomes: [
      'ICP definition & targeted list building',
      'Email warm-up + multi-channel sequencing',
      'Inbox management & reply handling',
      'Weekly meetings-booked dashboard',
    ],
    demandTier: 'highest',
    demandLabel: '🔥 Highest Demand',
    emoji: '🤖',
  },
  {
    id: 'S2',
    category: 'sales',
    name: 'AI GTM Engine',
    tagline: 'Done-For-You Revenue System',
    description:
      'A live go-to-market execution engine, not a consulting deck. We build and activate your outreach system within 7 days. Ideal for founders targeting US, UK, or Gulf markets who need pipeline — not strategy slides.',
    outcomes: [
      'Market entry playbook with live system',
      'Live outbound engine active within 7 days',
      'Multi-market targeting (US / UK / Gulf)',
      'Monthly GTM performance review',
    ],
    demandTier: 'highest',
    demandLabel: '🔥 Highest Demand',
    emoji: '🎯',
  },
  {
    id: 'S3',
    category: 'sales',
    name: 'AI Lead Generation & Prospecting',
    tagline: 'Find the Right Buyer, Every Time',
    description:
      'AI-powered buyer discovery and list building for B2B founders and exporters. We set up and manage tools like Apollo and Clay as a fully managed service — so you get qualified prospects without the setup headache.',
    outcomes: [
      'Verified B2B contact lists, built to your ICP',
      'Managed Apollo / Clay setup & operations',
      'Weekly fresh prospect pipeline delivered',
      'CRM-ready exports with enriched data',
    ],
    demandTier: 'highest',
    demandLabel: '🔥 Highest Demand',
    emoji: '🔍',
  },
  {
    id: 'S4',
    category: 'sales',
    name: 'WhatsApp AI Outreach System',
    tagline: 'Sell on the Channel Your Buyers Actually Use',
    description:
      'AI-native WhatsApp Business automation for lead nurturing, follow-ups, and sales conversions. 95% of Indian SMB sales happen over WhatsApp — we build the system that makes it scalable and measurable.',
    outcomes: [
      'WhatsApp Business API setup & compliance',
      'AI chatbot for 24/7 lead qualification',
      'Broadcast campaign sequences with tracking',
      'Full CRM sync for every conversation',
    ],
    demandTier: 'highest',
    demandLabel: '🔥 Highest Demand',
    emoji: '💬',
  },
  {
    id: 'S5',
    category: 'sales',
    name: 'AI CSO-as-a-Service',
    tagline: 'Fractional Chief Sales Officer, Powered by AI',
    description:
      'AI-powered sales leadership for B2B SMBs with no structured sales function. We act as your fractional CSO — defining territories, building your sales playbook, designing your pipeline, and reviewing deals weekly.',
    outcomes: [
      'ICP definition & territory mapping',
      'AI outreach system setup end-to-end',
      'Sales playbook + CRM pipeline design',
      'Monthly performance dashboard & deal review',
    ],
    demandTier: 'growing',
    demandLabel: '⚡ Growing',
    emoji: '👔',
  },
  {
    id: 'S6',
    category: 'sales',
    name: 'AI Export Accelerator',
    tagline: 'Win International Buyers with AI',
    description:
      'End-to-end AI-powered service to help Indian FMCG, textile, and pharma businesses find and close international buyers in the US, UK, UAE, and Southeast Asia. First-mover advantage: nobody else offers this as a packaged AI service.',
    outcomes: [
      'AI-powered buyer discovery across 4 markets',
      'Personalised cold outreach to distributors & importers',
      'Export pitch deck creation',
      'LinkedIn + WhatsApp automation for international leads',
    ],
    demandTier: 'premium',
    demandLabel: '🧊 Premium',
    emoji: '🌍',
  },
  {
    id: 'M1',
    category: 'marketing',
    name: 'AI Content Engine',
    tagline: '30 Days of Content in 3 Hours',
    description:
      'AI-generated, human-reviewed content at scale. We produce 60 social posts, 4 newsletters, and 8 blog drafts per month — so you look active on LinkedIn, Instagram, and WhatsApp without spending your time on it.',
    outcomes: [
      '60 social posts/month (LinkedIn, Instagram, WhatsApp)',
      '4 newsletters + 8 blog drafts/month',
      'Human review layer for brand accuracy',
      'Delivered via content calendar with scheduling',
    ],
    demandTier: 'highest',
    demandLabel: '🔥 Highest Demand',
    emoji: '✍️',
  },
  {
    id: 'M2',
    category: 'marketing',
    name: 'AI CMO-as-a-Service',
    tagline: 'Fractional Chief Marketing Officer, Powered by AI',
    description:
      'Your AI-powered marketing brain. We act as your fractional CMO — running monthly brand and campaign strategy, overseeing paid ads, monitoring competitors, and delivering CMO-level reporting with clear priorities each month.',
    outcomes: [
      'Monthly brand + campaign strategy',
      'AI content calendar with full execution',
      'Meta & Google Ads oversight',
      'Competitor monitoring + quarterly GTM review',
    ],
    demandTier: 'growing',
    demandLabel: '⚡ Growing',
    emoji: '📊',
  },
  {
    id: 'M3',
    category: 'marketing',
    name: 'AI Brand Voice & Positioning Sprint',
    tagline: 'The Foundation Every Campaign Needs',
    description:
      'A focused 2-week sprint that uses AI to define your brand voice, messaging hierarchy, and content framework — before a single campaign runs. Includes competitor audit, positioning workshop, persona development, and a starter content bank.',
    outcomes: [
      'AI-powered competitor messaging audit',
      'Messaging framework: tagline, elevator pitch, email tone',
      '3 audience personas built with AI',
      'Starter bank: 20 posts + 5 email templates',
    ],
    demandTier: 'growing',
    demandLabel: '⚡ Growing',
    emoji: '🎨',
  },
  {
    id: 'M4',
    category: 'marketing',
    name: 'AI Social Media Management',
    tagline: 'Real ROI from Social, Finally',
    description:
      'An AI-driven alternative to traditional social media agencies — with analytics that prove impact. We create, schedule, and optimise content across platforms, replacing the ₹15–50K/month agency spend that delivers zero measurable results.',
    outcomes: [
      'Multi-platform content creation & scheduling',
      'AI-driven performance analytics dashboard',
      'Monthly growth and engagement report',
      'Audience targeting refinement each quarter',
    ],
    demandTier: 'growing',
    demandLabel: '⚡ Growing',
    emoji: '📱',
  },
  {
    id: 'M5',
    category: 'marketing',
    name: 'AI SEO & Search Strategy',
    tagline: 'Built for the Post-AI Overview World',
    description:
      'SEO has changed fundamentally since Google\'s AI Overviews update. We build AI-native search strategies that are optimised for both traditional search and the new AI-powered answer engines — keeping your business visible where buyers look.',
    outcomes: [
      'AI-native keyword and topic strategy',
      'Content optimised for AI Overviews & LLMs',
      'Technical SEO audit + fix implementation',
      'Monthly ranking and visibility report',
    ],
    demandTier: 'growing',
    demandLabel: '⚡ Growing',
    emoji: '🔎',
  },
  {
    id: 'O1',
    category: 'operations',
    name: 'AI Operations Audit + Build',
    tagline: 'Cut 20 Hours of Manual Work Per Week',
    description:
      'We start with a free 45-minute operations audit to identify your biggest time-wasters, then build a custom automation system using Make.com, n8n, Zoho, or HubSpot. The pain point is time, not technology — and we solve it.',
    outcomes: [
      'Free 45-min operations audit to find bottlenecks',
      'Custom automation build across your tool stack',
      'Zoho / HubSpot / Make.com / n8n integrations',
      '\"Set it and forget it\" delivery with handoff training',
    ],
    demandTier: 'highest',
    demandLabel: '🔥 Highest Demand',
    emoji: '⚙️',
  },
  {
    id: 'O2',
    category: 'operations',
    name: 'AI CRM Integration & Setup',
    tagline: 'Make Your CRM Actually Work',
    description:
      'Most SMBs have a CRM nobody uses properly. We do AI-led CRM setup, data migration, pipeline design, and team training — turning your CRM from a ghost town into your single source of revenue truth.',
    outcomes: [
      'Full CRM setup, configuration & data migration',
      'AI-powered pipeline stages & deal scoring',
      'Team training and adoption playbook',
      'Monthly CRM health check & optimisation',
    ],
    demandTier: 'growing',
    demandLabel: '⚡ Growing',
    emoji: '🗂️',
  },
  {
    id: 'O3',
    category: 'operations',
    name: 'AI Competitive Intelligence Retainer',
    tagline: 'Always Know What Your Competitors Are Doing',
    description:
      'Monthly AI-powered monitoring of competitor pricing, campaigns, hiring, product launches, and social activity — delivered as a clear weekly signal report and a monthly strategic brief with action recommendations.',
    outcomes: [
      'Weekly competitor signal report',
      'Pricing & positioning tracker (updated continuously)',
      'LinkedIn + ad library monitoring',
      'Monthly strategic brief with recommended actions',
    ],
    demandTier: 'growing',
    demandLabel: '⚡ Growing',
    emoji: '🕵️',
  },
  {
    id: 'O4',
    category: 'operations',
    name: 'AI Data Analytics & Reporting',
    tagline: 'Stop Flying Blind on Your Own Business',
    description:
      'AI-powered dashboards that translate your raw business data into plain-language weekly intelligence. No data science degree required — just clear answers to the questions that drive your next decision.',
    outcomes: [
      'Custom AI dashboard built on your data sources',
      'Weekly business intelligence report in plain language',
      'KPI tracking across sales, marketing & ops',
      'Anomaly detection & auto-alerts on key metrics',
    ],
    demandTier: 'growing',
    demandLabel: '⚡ Growing',
    emoji: '📈',
  },
  {
    id: 'T1',
    category: 'transformation',
    name: 'AI Transformation Roadmap',
    tagline: '90-Day AI Adoption Sprint',
    description:
      'A structured 90-day programme to take your business from AI-curious to AI-native. Three phases: Diagnose (weeks 1–2), Deploy (weeks 3–8), Dominate (weeks 9–12). SMBs buy sprints, not open-ended retainers — this is built accordingly.',
    outcomes: [
      'Phase 1 Diagnose: Full AI readiness audit',
      'Phase 2 Deploy: Priority AI systems built & launched',
      'Phase 3 Dominate: Adoption, training & optimisation',
      'Executive AI playbook delivered at close',
    ],
    demandTier: 'premium',
    demandLabel: '🧊 Premium',
    emoji: '🏗️',
  },
  {
    id: 'T2',
    category: 'transformation',
    name: 'AI Business Intelligence',
    tagline: 'Enterprise-Grade Insight, SMB Price',
    description:
      'A comprehensive AI-powered BI layer that connects all your data sources — CRM, ads, ops, finance — into a single intelligence hub. Weekly dashboards, monthly executive briefs, and quarterly strategic reviews.',
    outcomes: [
      'Unified data layer across all business systems',
      'AI-generated weekly executive dashboard',
      'Monthly performance brief with strategic priorities',
      'Quarterly board-ready reporting package',
    ],
    demandTier: 'growing',
    demandLabel: '⚡ Growing',
    emoji: '🧠',
  },
];
